spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/culinary_blog
    username: postgres
    password: kacper
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

application:
  security:
    jwt:
      secret-key: ef17bc67e97b035b5a910411dfe24aa1669286320fc00bfa74fe667ac910bd3f

image:
  folder: culinaryBlogApi\src\main\resources\static\image\
